server:
  port: 8080
  servlet:
    context-path: /app
spring:
  application:
    name: core-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb;Mode=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  mvc:
    hidden-method:
      filter:
        enabled: true